project:
  type: website

website:
  title: "parquet_viewer"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Repo
            href:  https://github.com/DOH-PXC5303/parquet_viewer/
          - text: Report a Bug
            href:  https://github.com/DOH-PXC5303/parquet_viewer/issues/

format:
  html:
    theme: cosmo
    toc: false

